echo VerifyModeline('vi: nosi')
echo VerifyModeline('vim: ai:tw=20')
echo VerifyModeline('vim: ai:tw:si')
echo VerifyModeline('vim: ai :tw:si')
echo VerifyModeline('vim: ai : tw : si')
echo VerifyModeline('vim: ai :: tw :: si')
echo VerifyModeline('vim: ai : : tw : : si')
echo VerifyModeline('vim: ai :  : tw : : : si ::: foo')
echo VerifyModeline('vim: ai: tw=20')
echo VerifyModeline('vim: ai :tw=20')
echo VerifyModeline('vim: ai : tw=20')
echo VerifyModeline('vim: ai : tw =20')
echo VerifyModeline('vim: noai:tw=20:')
echo VerifyModeline('vim: noai:tw=20:si: ')
" false positive until actual option names are detected
echo VerifyModeline('vim: noai:tw=20:si: blah')

echo VerifyModeline('vim620:  ai:tw=79:nosi')
echo VerifyModeline('foo vi:  ai:tw=79:nosi')
echo VerifyModeline('foo vim:  ai:tw=79:nosi')
echo VerifyModeline('foo vim560:  ai:tw=79:nosi')
echo VerifyModeline('foo ex:  ai:tw=79:nosi')
echo VerifyModeline('   vi:  ai:tw=79:nosi')
echo VerifyModeline('   vim:  ai:tw=79:nosi')
echo VerifyModeline('   vim700:  ai:tw=79:nosi')
echo VerifyModeline('   ex:  ai:tw=79:nosi')

echo VerifyModeline('vi: ai:tw=79:nosi')
echo VerifyModeline('vim: ai:tw=79:nosi')
echo VerifyModeline('vim620: ai:tw=79:nosi')
echo VerifyModeline('foo vi: ai:tw=79:nosi')
echo VerifyModeline('foo vim: ai:tw=79:nosi')
echo VerifyModeline('foo vim560: ai:tw=79:nosi')
echo VerifyModeline('foo ex: ai:tw=79:nosi')
echo VerifyModeline('   vi: ai:tw=79:nosi')
echo VerifyModeline('   vim: ai:tw=79:nosi')
echo VerifyModeline('   vim700: ai:tw=79:nosi')
echo VerifyModeline('   ex: ai:tw=79:nosi')
