echo VerifyModeline('vi: o')
echo VerifyModeline('vim: o')
echo VerifyModeline('vim620: o')
echo VerifyModeline('foo vi: o')
echo VerifyModeline('foo vim: o')
echo VerifyModeline('foo vim560: o')
echo VerifyModeline('foo ex: o')
echo VerifyModeline('   vi: o')
echo VerifyModeline('   vim: o')
echo VerifyModeline('   vim700: o')
echo VerifyModeline('   ex: o')

echo VerifyModeline('vi:o')
echo VerifyModeline('vim:o')
echo VerifyModeline('vim620:o')
echo VerifyModeline('foo vi:o')
echo VerifyModeline('foo vim:o')
echo VerifyModeline('foo vim560:o')
echo VerifyModeline('foo ex:o')
echo VerifyModeline('   vi:o')
echo VerifyModeline('   vim:o')
echo VerifyModeline('   vim700:o')
echo VerifyModeline('   ex:o')
