echo VerifyModeline('vi: set o:')
echo VerifyModeline('vim: set o:')
echo VerifyModeline('vim620: set o:')
echo VerifyModeline('foo vi: set o:')
echo VerifyModeline('foo vim: set o:')
echo VerifyModeline('foo vim560: set o:')
echo VerifyModeline('foo ex: set o:')
echo VerifyModeline('   vi: set o:')
echo VerifyModeline('   vim: set o:')
echo VerifyModeline('   vim700: set o:')
echo VerifyModeline('   ex: set o:')

echo VerifyModeline('vi: se o:')
echo VerifyModeline('vim: se o:')
echo VerifyModeline('vim620: se o:')
echo VerifyModeline('foo vi: se o:')
echo VerifyModeline('foo vim: se o:')
echo VerifyModeline('foo vim560: se o:')
echo VerifyModeline('foo ex: se o:')
echo VerifyModeline('   vi: se o:')
echo VerifyModeline('   vim: se o:')
echo VerifyModeline('   vim700: se o:')
echo VerifyModeline('   ex: se o:')

echo VerifyModeline('vi:set o:')
echo VerifyModeline('vim:set o:')
echo VerifyModeline('vim620:set o:')
echo VerifyModeline('foo vi:set o:')
echo VerifyModeline('foo vim:set o:')
echo VerifyModeline('foo vim560:set o:')
echo VerifyModeline('foo ex:set o:')
echo VerifyModeline('   vi:set o:')
echo VerifyModeline('   vim:set o:')
echo VerifyModeline('   vim700:set o:')
echo VerifyModeline('   ex:set o:')

echo VerifyModeline('vi:se o:')
echo VerifyModeline('vim:se o:')
echo VerifyModeline('vim620:se o:')
echo VerifyModeline('foo vi:se o:')
echo VerifyModeline('foo vim:se o:')
echo VerifyModeline('foo vim560:se o:')
echo VerifyModeline('foo ex:se o:')
echo VerifyModeline('   vi:se o:')
echo VerifyModeline('   vim:se o:')
echo VerifyModeline('   vim700:se o:')
echo VerifyModeline('   ex:se o:')

" text after trailing : ok

echo VerifyModeline('vi: set o : blah')
echo VerifyModeline('vim: set o : blah')
echo VerifyModeline('vim620: set o : blah')
echo VerifyModeline('foo vi: set o : blah')
echo VerifyModeline('foo vim: set o : blah')
echo VerifyModeline('foo vim560: set o : blah')
echo VerifyModeline('foo ex: set o : blah')
echo VerifyModeline('   vi: set o : blah')
echo VerifyModeline('   vim: set o : blah')
echo VerifyModeline('   vim700: set o : blah')
echo VerifyModeline('   ex: set o : blah')

echo VerifyModeline('vi: se o : blah')
echo VerifyModeline('vim: se o : blah')
echo VerifyModeline('vim620: se o : blah')
echo VerifyModeline('foo vi: se o : blah')
echo VerifyModeline('foo vim: se o : blah')
echo VerifyModeline('foo vim560: se o : blah')
echo VerifyModeline('foo ex: se o : blah')
echo VerifyModeline('   vi: se o : blah')
echo VerifyModeline('   vim: se o : blah')
echo VerifyModeline('   vim700: se o : blah')
echo VerifyModeline('   ex: se o : blah')

echo VerifyModeline('vi:set o : blah')
echo VerifyModeline('vim:set o : blah')
echo VerifyModeline('vim620:set o : blah')
echo VerifyModeline('foo vi:set o : blah')
echo VerifyModeline('foo vim:set o : blah')
echo VerifyModeline('foo vim560:set o : blah')
echo VerifyModeline('foo ex:set o : blah')
echo VerifyModeline('   vi:set o : blah')
echo VerifyModeline('   vim:set o : blah')
echo VerifyModeline('   vim700:set o : blah')
echo VerifyModeline('   ex:set o : blah')

echo VerifyModeline('vi:se o : blah')
echo VerifyModeline('vim:se o : blah')
echo VerifyModeline('vim620:se o : blah')
echo VerifyModeline('foo vi:se o : blah')
echo VerifyModeline('foo vim:se o : blah')
echo VerifyModeline('foo vim560:se o : blah')
echo VerifyModeline('foo ex:se o : blah')
echo VerifyModeline('   vi:se o : blah')
echo VerifyModeline('   vim:se o : blah')
echo VerifyModeline('   vim700:se o : blah')
echo VerifyModeline('   ex:se o : blah')
